# Generated by Django 6.0.7 on 2026-08-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('sales_executive', models.CharField(blank=True, max_length=100)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_closing_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(choices=[('Website', 'Website'), ('Dealer', 'Dealer'), ('Architect', 'Architect'), ('Tender', 'Tender'), ('Walk-in', 'Walk-in')], default='Website', max_length=30)),
                ('status', models.CharField(choices=[('New', 'New'), ('Follow-up', 'Follow-up'), ('Quotation', 'Quotation'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('drawing', models.FileField(blank=True, null=True, upload_to='crm/drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='customers.customer')),
            ],
        ),
    ]
